name: Generate Asciidoc JSON

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install packages
      run: sudo apt install -y --no-install-recommends zlib1g-dev pkg-config libgmp-dev curl
    - name: Check out repository code
      uses: actions/checkout@HEAD
      with:
        submodules: true
    - name: Ensure pre-commit checks pass
      run: pip install pre-commit && pre-commit run --all-files --show-diff-on-failure --color=always
    - name: Install sail from binary
      run: |
        sudo mkdir -p /usr/local
        curl --location https://github.com/rems-project/sail/releases/download/0.18-linux-binary/sail.tar.gz | sudo tar xvz --directory=/usr/local --strip-components=1
    - name: Build Asciidoc JSON bundle
      run: make sail_doc/riscv_RV64.json
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: riscv_RV64.json
        path: sail_doc/riscv_RV64.json
